### ISSUE TITLE
showManagePreferences crashes when AppNotice is used together with Facebook Sdk

### ISSUE THREAD

**Issue by jakubvimn** [Crownpeak/AppNotice_Triangle_android_aar#22]
1. Add dependency to the Facebook SDK in version 4.33.0
2. Call `appNotice.showManagePreferences()`

Result:
`
05-18 15:33:17.545 24780-24780/com.mtvn.vh1android E/com.vmnExceptionHandler (18/05/2018-15:33:17): Exception handled: 
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mtvn.vh1android/com.evidon.privacy.appnoticesdk.AppNotice_Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.evidon.privacy.appnoticesdk.AppNotice_Activity.onCreate(SourceFile:61)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
`

Reason:
Facebook SDK uses `ActivityLifecycleCallbacks` to add extra to every single `Activity` in the application. The `AppNotice_Activity` assumes that if any extras exists, there's a valid extra with key `FRAGMENT_TYPE`, which is not true in this case.

Solution:
Add checking of the extra with key `FRAGMENT_TYPE` exists before using it.

**Comment by vinaychencharam** [comment]
Hi @jakubvimn thanks for the explanation. Try the new version of AppNoticeSDK (2.2.2.4). Hope this works for you. LMK  if you have any issues. Thanks

**Comment by jakubvimn** [comment]
Thanks a lot. I've created a ticket in our queue to try the new version. I'll let you know when we complete it.

**Comment by jakubvimn** [comment]
We checked the version 2.2.4 and the problem does not occur any longer. Thanks for you help.
